#!/bin/csh

#
# Install
#

cd `dirname $0` && source ./Configuration

# Create a copy of the default index page that has the proper FTPURL
# substituted in it and copy it to the FTP report directory.
#
rm -f index.html
sed "s/FTPURL_GOES_HERE/$FTPURL/" index.html.default > index.html
cp index.html ${FTPREPORTDIR}

#
# directories
#

if ( ! -d ${REPORTDIR} ) then
    mkdir -p ${REPORTDIR}
endif

if ( ! -d ${REPORTOUTPUTDIR} ) then
    mkdir -p ${REPORTOUTPUTDIR}
endif

if ( ! -d ${REPORTOUTPUTDIR}/mgimarkerfeed ) then
    mkdir -p ${REPORTOUTPUTDIR}/mgimarkerfeed
endif

if ( ! -d ${REPORTLOGSDIR} ) then
    mkdir -p ${REPORTLOGSDIR}
endif

if ( ! -d ${INPARANOIDDIR} ) then
    mkdir -p ${INPARANOIDDIR}
endif

# provide a link to the Mammalian Phenotype vocabulary
cd ${REPORTOUTPUTDIR}
foreach f (${MPFILES})
    rm -rf $f
    ln -s ${MPVOCSOURCE}/$f .
end

# provide a link to the Adult Mouse Anatomy vocabulary
cd ${REPORTOUTPUTDIR}
foreach f (${MAFILES})
    rm -rf $f
    ln -s ${MAVOCSOURCE}/$f .
end

#
# permissions
#

cd ${PUBRPTS}
chmod 664 Configuration* HISTORY *.html
chmod 775 *.sh */*.py */*.sql Install
chmod 775 daily weekly
