#!/bin/csh

#
# Install
#

cd `dirname $0` && source ./Configuration

# create server side include file for ftp url
echo "$FTPURL" > includes/ftp_url.html

# link index page from FTP report directory
rm -rf ${FTPREPORTDIR}/index.shtml ${FTPREPORTDIR}/index.html
rm -rf ${FTPREPORTDIR}/includes
cp ${PUBRPTS}/index.shtml ${FTPREPORTDIR}/index.shtml
cp -r ${PUBRPTS}/includes ${FTPREPORTDIR}/includes

#
# permissions
#

chmod 664 Configuration.* HISTORY *.shtml
chmod 775 *.csh */*.py */*.sql Install

#
# directories
#

if ( ! -d ${PUBREPORTDIR} ) then
    mkdir -p ${PUBREPORTDIR}
endif

if ( ! -d ${REPORTOUTPUTDIR} ) then
    mkdir -p ${REPORTOUTPUTDIR}
endif

if ( ! -d ${REPORTOUTPUTDIR}/mgimarkerfeed ) then
    mkdir -p ${REPORTOUTPUTDIR}/mgimarkerfeed
endif

if ( ! -d ${REPORTLOGSDIR} ) then
    mkdir -p ${REPORTLOGSDIR}
endif

if ( ! -d ${IPHONEARCHIVE} ) then
    mkdir -p ${IPHONEARCHIVE}
endif

if ( ! -d ${CVDCDIR} ) then
    mkdir -p ${CVDCDIR}
endif

if ( ${SERVER_NAME} == "bhmgiapp01" ||  ${SERVER_NAME} == "bhmgidevapp01" ) then
    # provide a link to the Mammalian Phenotype vocabulary
    cd ${REPORTOUTPUTDIR}
    foreach f (${MPFILES})
        rm -rf $f
        ln -s ${MPVOCSOURCE}/$f .
    end

    # provide a link to the Adult Mouse Anatomy vocabulary
    cd ${REPORTOUTPUTDIR}
    foreach f (${MAFILES})
        rm -rf $f
        ln -s ${MAVOCSOURCE}/$f .
    end
endif

cd ${FTPREPORTDIR}
ln -s index.shtml index.html
