#!/bin/csh

#
# Install
#

cd `dirname $0` && source ./Configuration

sed "s/ftp.informatics.jax.org/$FTPURL/" index.html > index.html.new
mv -f index.html.new index.html

foreach i (index.html)
	rcp -r $i ${FTPREPORTDIR}
end

cd daily
set toEdit=`grep -l radar *`
foreach i ($toEdit)
sed "s/radar/$RADAR_DBNAME/g" $i > $i.new
mv -f $i.new $i
end

#
# directories
#

if ( ! -d ${REPORTDIR} ) then
	mkdir ${REPORTDIR}
endif

if ( ! -d ${REPORTOUTPUTDIR} ) then
	mkdir ${REPORTOUTPUTDIR}
endif

if ( ! -d ${REPORTOUTPUTDIR}/mgimarkerfeed ) then
	mkdir ${REPORTOUTPUTDIR}/mgimarkerfeed
endif

if ( ! -d ${REPORTLOGSDIR} ) then
	mkdir ${REPORTLOGSDIR}
endif

if ( ! -d ${INPARANOIDDIR} ) then
	mkdir ${INPARANOIDDIR}
endif

# provide a link to the Mammalian Phenotype vocabulary
cd ${REPORTOUTPUTDIR}
foreach f (${MPFILES})
rm -rf $f
ln -s ${MPVOCSOURCE}/$f .
end

# provide a link to the Adult Mouse Anatomy vocabulary
cd ${REPORTOUTPUTDIR}
foreach f (${MAFILES})
rm -rf $f
ln -s ${MAVOCSOURCE}/$f .
end

#
# permissions
#

cd ${PUBRPTS}
chmod 664 Configuration* HISTORY *.html
chmod 775 *.sh */*.py */*.sql Install
chmod 775 daily monthly weekly

