
'''
#
# MGI_HpMpLexical.py
#
# Report:

#
# Usage:
#       MGI_HpMpLexical.py
#
# Used by:
#       Internal Report for Pheno Group
#
# Notes:
#
#   Main Requirements: 
#     https://mgi-jira.atlassian.net/browse/WTS2-1391
#   Match Type Requirements (Part 4 below): 
#     https://mgi-jira.atlassian.net/browse/FL2-526
#
#   This report has 4 main textual matching sections, each with different requirements:
#     Part 1) HP Term -> MP Term
#     Part 2) HP Term -> MP Synonym
#     Part 3) HP Synonym -> MP Term
#     Part 4) HP Synonym -> MP Synonym (with some being invalid and discarded)
#
#   Column Order: 
#     1 - HP ID
#     2 - HP term label
#     3 - predicate_id; skos Match type - see requirements
#     4 - confidence; see requirements
#     5 - MP ID
#     6 - MP term label
#     7 - mapping_justification; semapv:LexicalMatching
#     8 - mapping_tool; MGI_pipeline
#     9 - mapping_date; format YYYY-MM-DD
#     10 - subject_match_field - [field from MP that matched]
#     11 - object_match_field - [field from HP that matched]
#     12 - matched text string
#
# History:
#
# pf	03/06/2026
#	 - initial deployment
#
#
'''
 
import sys
import os
import reportlib
import db
import mgi_utils

CRT = reportlib.CRT
TAB = reportlib.TAB

db.setTrace()
currentDate = mgi_utils.date('%Y-%m-%d')

fpReport  = reportlib.init('mp_hp_mgi_lex.sssom', outputdir = os.environ['REPORTOUTPUTDIR'], printHeading = None)

createDiscardFile = False

#
# Main
#

# add file header required for external parsing 
fpReport.write(
'''#mapping_set_id: https://w3id.org/sssom/commons/mouse-human/mappings/mp_hp_mgi_lex.sssom.tsv
#mapping_set_title: All mappings of MP terms to HPO terms generated by MGI
#mapping_set_description: "Mappings created by Mouse Genome Informatics (MGI) by lexical matches between term and synonym labels. Lexical mappings are made by comparing the text of each label and calling a match whenever the labels are identical. Term label to term label matches are all skos:exactMatch. Term label to synonym label are made depending on the synonym type (eg. exact synonym = exactMatch). For narrow and broad synonyms the match type is identical to synonym type when the match is HP term label to MP synonym label but reversed when it is MP term label to HP synonym label. Synonym to synonym matches are made for exact synonyms to any other type of synonym the same as for term label to synonym matches. Non-exact to non-exact synonym matches are currently only made for HP narrow to MP narrow (this is a broadMatch). The other possible matches either had no examples or gave incorrect matches and thus were not included in the mappings. Matches were reviewed manually during the creation of the mapping pipeline but are not routinely manually reviewed. Pipeline was created in 2024 and matches are updated regularly."
#creator_id:
# - orcid:0000-0003-4606-0597
# - ror:021sy4w91
#license: https://creativecommons.org/licenses/by/4.0/
#object_source: obo:hp
#subject_source: obo:mp
#curie_map:
# HP: http://purl.obolibrary.org/obo/HP_
# MP: http://purl.obolibrary.org/obo/MP_
# skos: http://www.w3.org/2004/02/skos/core#
# orcid: https://orcid.org/
# ror: https://ror.org/
# wikidata: https://www.wikidata.org/wiki/
# obo: http://purl.obolibrary.org/obo/
# semapv: https://w3id.org/semapv/vocab/
'''
)

# add column headers
fpReport.write('object_id' + TAB)
fpReport.write('object_label' + TAB)
fpReport.write('predicate_id' + TAB)
fpReport.write('confidence' + TAB)
fpReport.write('subject_id' + TAB)
fpReport.write('subject_label' + TAB)
fpReport.write('mapping_justification' + TAB)
fpReport.write('mapping_tool' + TAB)
fpReport.write('mapping_date' + TAB)
fpReport.write('object_match_field' + TAB)
fpReport.write('subject_match_field' + TAB)
fpReport.write('match_string' + CRT)

#
# Part 1: handle HP Term to MP Term lexical matches
#

hpTermToMpTerm = db.sql('''
  select
    vtHp._term_key as HP_Term_key,
    accHp.accid as HumanID,
    vtHp.term as HP_Term,
    vtMp._term_key as MP_Term_key,
    accMp.accid as MouseID,
    vtMp.term as MP_Term
  from 
    voc_term vtMp, 
    voc_term vtHp,
    acc_accession accMp,
    acc_accession accHp
  where lower(vtMp.term) = lower(vtHp.term)
    and vtMp._vocab_key = 5
    and vtMp.isobsolete = 0
    and vtHp._vocab_key = 106
    and vtHp.isobsolete = 0
    and vtMp._term_key = accMp._object_key
    and accMp._mgitype_key = 13
    and accMp.preferred = 1
    and vtHp._term_key = accHp._object_key
    and accHp._mgitype_key = 13
    and accHp.preferred = 1
  order by HP_Term
''', 'auto')

for r in hpTermToMpTerm:

  fpReport.write(r['HumanID'] + TAB)
  fpReport.write(r['HP_Term'] + TAB)
  fpReport.write('skos:exactMatch' + TAB)
  fpReport.write('1' + TAB)
  fpReport.write(r['MouseID'] + TAB)
  fpReport.write(r['MP_Term'] + TAB)
  fpReport.write('semapv:LexicalMatching' + TAB)
  fpReport.write('MGI_pipeline' + TAB)
  fpReport.write(currentDate + TAB)
  fpReport.write('MP term label' + TAB)
  fpReport.write('HP term label' + TAB)
  fpReport.write(r['HP_Term'] + CRT) # matched text


#
# Part 2: handle HP Term to MP Synonym lexical matches
#

hpTermToMpSyn = db.sql('''
  select  
    vtHp._term_key as HP_Term_key,
    accHp.accid as HumanID,
    vtHp.term as HP_Term,
    vtMp._term_key as MP_Term_key,
    accMp.accid as MouseID,
    vtMp.term as MP_Term,
    msMp.synonym as MP_Term_Syn,
    mstMp.synonymtype as MP_Syn_Type,
    mstMp._synonymtype_key
  from 
    voc_term vtMp, 
    voc_term vtHp,
    mgi_synonym msMp,
    mgi_synonymtype mstMp,
    acc_accession accMp,
    acc_accession accHp
  where lower(msMp.synonym) = lower(vtHp.term)
    and vtMp._vocab_key = 5
    and vtMp.isobsolete = 0
    and vtMp._term_key = msMp._object_key
    and vtHp._vocab_key = 106
    and vtHp.isobsolete = 0
    and msMp._mgitype_key = 13
    and vtMp._term_key = accMp._object_key
    and accMp._mgitype_key = 13
    and accMp.preferred = 1
    and vtHp._term_key = accHp._object_key
    and accHp._mgitype_key = 13
    and accHp.preferred = 1
    and msMp._synonymtype_key = mstMp._synonymtype_key
    and msMp._synonymtype_key in (1020, 1019, 1018, 1017) 
  order by HP_Term, mstMp._synonymtype_key
''', 'auto')

for r in hpTermToMpSyn:

  # pre-generate a few values; see requirements
  predicate = 'skos:' + r['MP_Syn_Type'] + 'Match'
  confidence = '0.8'
  if (r['MP_Syn_Type'] == 'exact'):
    confidence = '1'

  fpReport.write(r['HumanID'] + TAB)
  fpReport.write(r['HP_Term'] + TAB)
  fpReport.write(predicate + TAB)
  fpReport.write(confidence + TAB)
  fpReport.write(r['MouseID'] + TAB)
  fpReport.write(r['MP_Term'] + TAB)
  fpReport.write('semapv:LexicalMatching' + TAB)
  fpReport.write('MGI_pipeline' + TAB)
  fpReport.write(currentDate + TAB)
  fpReport.write(r['MP_Syn_Type'] + ' Synonym' + TAB)
  fpReport.write('HP term label' + TAB)
  fpReport.write(r['HP_Term'] + CRT) # matched text


#
# Part 3: handle HP Syn to MP term lexical matches
#

mpTermToHpSyn = db.sql('''
  select  
    vtHP._term_key as HP_Term_key,
    accHP.accid as HumanID,
    vtHP.term as HP_Term,
    vtMP._term_key as MP_Term_key,
    accMP.accid as MouseID,
    vtMP.term as MP_Term,
    msHP.synonym as HP_Term_Syn,
    mstHP.synonymtype as HP_Syn_Type,
    mstHP._synonymtype_key
  from 
    voc_term vtMP, 
    voc_term vtHP,
    mgi_synonym msHP,
    mgi_synonymtype mstHP,
    acc_accession accMP,
    acc_accession accHP
  where lower(msHP.synonym) = lower(vtMP.term)
    and vtMP._vocab_key = 5
    and vtMP.isobsolete = 0
    and vtHP._term_key = msHP._object_key
    and vtHP._vocab_key = 106
    and vtHP.isobsolete = 0
    and msHP._mgitype_key = 13
    and vtMP._term_key = accMP._object_key
    and accMP._mgitype_key = 13
    and accMP.preferred = 1
    and vtHP._term_key = accHP._object_key
    and accHP._mgitype_key = 13
    and accHP.preferred = 1
    and msHP._synonymtype_key = mstHP._synonymtype_key
    and msHP._synonymtype_key in (1020, 1019, 1018, 1017) 
  order by HP_Term, mstHP._synonymtype_key
''', 'auto')

for r in mpTermToHpSyn:

  # pre-generate a few values for this report row; see requirements
  predicate = 'skos:' + r['HP_Syn_Type'] + 'Match'
  confidence = '0.8'
  if (r['HP_Syn_Type'] == 'exact'):
    confidence = '1'

  fpReport.write(r['HumanID'] + TAB)
  fpReport.write(r['HP_Term'] + TAB)
  fpReport.write(predicate + TAB)
  fpReport.write(confidence + TAB)
  fpReport.write(r['MouseID'] + TAB)
  fpReport.write(r['MP_Term'] + TAB)
  fpReport.write('semapv:LexicalMatching' + TAB)
  fpReport.write('MGI_pipeline' + TAB)
  fpReport.write(currentDate + TAB)
  fpReport.write('MP term label' + TAB)
  fpReport.write(r['HP_Syn_Type'] + ' Synonym' + TAB)
  fpReport.write(r['MP_Term'] + CRT) # matched text


#
# Part 4: handle HP Syn to MP Syn lexical matches
#

hpSynToMpSyn = db.sql('''
  select  
    vtHP._term_key as HP_Term_key,
    accHP.accid as HumanID,
    vtHP.term as HP_Term,
    vtMP._term_key as MP_Term_key,
    accMP.accid as MouseID,
    vtMP.term as MP_Term,
    msMP.synonym as MP_Term_Syn,
    mstMP.synonymtype as MP_Syn_Type,
    msHP.synonym as HP_Term_Syn,
    mstHP.synonymtype as HP_Syn_Type
  from 
    voc_term vtMP, 
    voc_term vtHP,
    mgi_synonym msMP,
    mgi_synonym msHP,
    mgi_synonymtype mstMP,
    mgi_synonymtype mstHP,
    acc_accession accMP,
    acc_accession accHP
  where lower(msMP.synonym) = lower(msHP.synonym)
    and vtMP._vocab_key = 5
    and vtMP.isobsolete = 0
    and vtMP._term_key = msMP._object_key
    and msMP._mgitype_key = 13
    and vtHP._vocab_key = 106
    and vtHP.isobsolete = 0
    and vtHP._term_key = msHP._object_key
    and msHP._mgitype_key = 13
    and vtMP._term_key = accMP._object_key
    and accMP._mgitype_key = 13
    and accMP.preferred = 1
    and vtHP._term_key = accHP._object_key
    and accHP._mgitype_key = 13
    and accHP.preferred = 1
    and msMP._synonymtype_key = mstMP._synonymtype_key
    and msHP._synonymtype_key = mstHP._synonymtype_key
    and msMP._synonymtype_key in (1020, 1019, 1018, 1017) 
    and msHP._synonymtype_key in (1020, 1019, 1018, 1017) 
  order by mstMP._synonymtype_key, mstHP._synonymtype_key, HP_Term 
''', 'auto')

# Specific HP vs MP synonym type combos require special handling, while
# some are invalid.
# Full requirements are in 'Match Type Requirements' linked in header.
def getSynToSynType (hpSynType, mpSynType):

  type = ''  

  if (hpSynType == 'exact'):
    type = mpSynType
  elif (hpSynType == 'narrow'):
    if (mpSynType == 'exact' or mpSynType == 'narrow'):
      type = 'broad'
  elif (hpSynType == 'broad'):
    if (mpSynType == 'exact'):
      type = 'narrow'
  elif (hpSynType == 'related'):
    if (mpSynType == 'exact' or mpSynType == 'narrow'):
      type = 'related'

  return type

# for each row in syn to syn matches
for r in hpSynToMpSyn:

  # pre-generate a few values
  confidence = '0.8'
  if (r['MP_Syn_Type'] == 'exact' and r['HP_Syn_Type'] == 'exact'):
    confidence = '0.9'
  comboType = getSynToSynType(r['HP_Syn_Type'], r['MP_Syn_Type'])

  # write this row only if syn-to-syn combo is valid
  if (comboType != ''):
    fpReport.write(r['HumanID'] + TAB)
    fpReport.write(r['HP_Term'] + TAB)
    fpReport.write('skos:' + comboType + 'Match' + TAB)
    fpReport.write(confidence + TAB)
    fpReport.write(r['MouseID'] + TAB)
    fpReport.write(r['MP_Term'] + TAB)
    fpReport.write('semapv:LexicalMatching' + TAB)
    fpReport.write('MGI_pipeline' + TAB)
    fpReport.write(currentDate + TAB)
    fpReport.write(r['MP_Syn_Type'] + ' Synonym' + TAB)
    fpReport.write(r['HP_Syn_Type'] + ' Synonym' + TAB)
    fpReport.write(r['MP_Term_Syn'] + CRT) # matched text

# some syn to syn matches need be discarded; save those, if requested
if (createDiscardFile): 
  
  fpDiscard = reportlib.init('mp_hp_mgi_discard',   outputdir = os.environ['REPORTOUTPUTDIR'], printHeading = None)
  
  # for each row in syn to syn matches
  for r in hpSynToMpSyn:
    comboType = getSynToSynType(r['HP_Syn_Type'], r['MP_Syn_Type'])
    if (comboType == ''):
      fpDiscard.write(r['HumanID'] + TAB)
      fpDiscard.write(r['HP_Term'] + TAB)
      fpDiscard.write(r['MouseID'] + TAB)
      fpDiscard.write(r['MP_Term'] + TAB)
      fpDiscard.write(r['MP_Syn_Type'] + ' MP Synonym' + TAB)
      fpDiscard.write(r['HP_Syn_Type'] + ' HP Synonym' + TAB)
      fpDiscard.write(r['MP_Term_Syn'] + CRT) # matched text

  reportlib.finish_nonps(fpDiscard)

# close main file pointer
reportlib.finish_nonps(fpReport)

