#!/usr/bin/env perl

#
# 8/1/2008 - sc - This script was given to us by the folks at UniProt
# We install it in depot and rdist it rather than cvs'ing it
# This script is dependent on the SwissKnife perl library
#
# 3/16/2015 - dbm - In order to get this script to work with Solaris or
# Linux, Perl needs to be invoked without a hardcoded path. The script
# was copied into the reports_db product for simplicity.
#

use strict;

use IO::File;

use SWISS::Entry;

my $inputfile = @ARGV[0];
my $fh = new IO::File $inputfile or
die "Cannot open input file $inputfile: $!";


$/ = "\n\/\/";
while(<$fh>) {
s/\r//g;
(my $entry_txt = $_) =~ s/^\s+//;
next unless $entry_txt;
$entry_txt .= "\n";
my $entry = SWISS::Entry->fromText( $entry_txt );
print $entry->toFasta();
} 
